# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- feature-ams-merged

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2b884e2c-17f6-402a-bc6e-bb19e87476ce'
  imageRepository: 'cems-ams'
  containerRegistry: 'polyuitsncsts.azurecr.io'
  dockerContextPath: '$(Build.SourcesDirectory)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile_ams'
  tag: '$(Build.BuildNumber)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: Default
      vmImage: $(vmImageName)
    steps:

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        buildContext: $(dockerContextPath)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags:
          $(tag)
