import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getMe } from './api/me';
import { getRefresh } from './api/refresh';
import * as userTypeApi from './api/userType';
import { resetSession } from './AppAction';

export const initApp = createAsyncThunk(
  'app/initApp',
  async (payload, thunkAPI) => {
    try {
      await getRefresh();
      const me = await getMe();

      if (!!me?.data?.success) {
        return me.data.data;
      }
    } catch (err) {
    }
    return thunkAPI.rejectWithValue("Not logged in.");
  }
);

export const getUserTypes = createAsyncThunk(
  'app/getUserTypes',
  async (payload, thunkAPI) => {
    const apiResponse = await userTypeApi.search(payload);
    return apiResponse.data;
  }
);

const initialState = {
  isAppLaunching: true,
  me: null,
  isLoggedIn: null,
  eventId: "",
  eventName: "",
  userTypes: {
    acceptAnyone: false,
    acceptAlumni: false,
    acceptStudent: false,
    acceptStaff: false,
    acceptGuest: false,
  }
};

export const AppSlice = createSlice(
  {
    name: 'app',
    initialState,
    reducers: {
      resetStore: () => initialState,
      stopAppLaunching: (state, action) => {
        state.isAppLaunching = false;
      },
      setEventName: (state, action) => {
        state.eventName = action.payload;
      },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(resetSession, (state, action) => {
          state.me = null;
          state.isLoggedIn = false;
          state.isAppLaunching = false;
        })
        .addCase(initApp.fulfilled, (state, action) => {
          state.me = action.payload;
          state.isLoggedIn = !!action.payload;
          state.isAppLaunching = false;
        })
        .addCase(initApp.rejected, (state, action) => {
          state.me = null;
          state.isLoggedIn = false;
          state.isAppLaunching = false;
        })
        .addCase(getUserTypes.fulfilled, (state, action) => {
          state.userTypes = action.payload.data;
        })
    },
  }
);

export default AppSlice;