import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getRefresh } from '../../../api/refresh';
import { getPing } from '../../../api/ping';

export const pingAsync = createAsyncThunk(
  'sessionTimeoutDialog/pingAsync',
  async (payload, thunkAPI) => {
    try {
      const ping = await getPing();

      if (!!ping?.data?.success) {
        return ping.data.data;
      }
    } catch (err) {
    }
    return thunkAPI.rejectWithValue("Not logged in.");
  }
);

export const refreshAsync = createAsyncThunk(
  'sessionTimeoutDialog/refreshAsync',
  async (payload, thunkAPI) => {
    try {
      const refresh = await getRefresh();
      const ping = await getPing();

      if (!!refresh?.data?.success && !!ping?.data?.success) {
        return ping.data.data;
      }
    } catch (err) {
    }
    return thunkAPI.rejectWithValue("Not logged in.");
  }
);

const initialState = {
  lastActivityAt: null,
};

export const SessionTimeoutDialogSlice = createSlice(
  {
    name: 'sessionTimeoutDialog',
    initialState,
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(pingAsync.fulfilled, (state, action) => {
          state.lastActivityAt = action.payload;
        })
        .addCase(refreshAsync.fulfilled, (state, action) => {
          state.lastActivityAt = action.payload;
        })
    },
  }
);

export default SessionTimeoutDialogSlice;